[package]
name = "array-map-json"
group = "fluvio"
version = "0.1.0"
apiVersion = "0.1.0"
description = "Flatten JSON array aggregates into JSON records"
license = "Apache-2.0"
visibility = "public"

[[params]]
name = "input"
description = "input description"
