[package]
name = "regex-text"
group = "fluvio"
version = "0.1.0"
apiVersion = "0.1.0"
description = "Regex transformations on arbitrary values"
license = "Apache-2.0"
visibility = "public"

[[params]]
name = "spec"
description = "Regex specification"